<a href="https://colab.research.google.com/github/ga642381/ML2021-Spring/blob/main/Pytorch/Pytorch_Tutorial.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
# pytorch Tutorial

In [3]:
import torch
import numpy as np

In [4]:
torch.__version__

'1.13.1+cpu'

In [5]:
tsr = torch.tensor([[1,2],[3,4],[5,6]]); tsr

tensor([[1, 2],
        [3, 4],
        [5, 6]])

In [6]:
tsr = torch.tensor([[1,2],[3,4],[5,6]], dtype=torch.float64); tsr

tensor([[1., 2.],
        [3., 4.],
        [5., 6.]], dtype=torch.float64)

In [7]:
tsr = torch.zeros([2,3]); tsr

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [8]:
tsr = torch.ones([2,3]); tsr

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [9]:
if torch.cuda.is_available():
    # Get the number of available GPUs
    num_gpus = torch.cuda.device_count()
    
    # Get the name of the current GPU
    current_gpu_name = torch.cuda.get_device_name(0)  # Assuming you have at least one GPU
    
    print(f"Number of available GPUs: {num_gpus}")
    print(f"Current GPU name: {current_gpu_name}")
       
    # Now, operations will be performed on the GPU by default if available
    cuda0 = torch.device('cuda:0')
    tsr = torch.tensor([[1,2],[3,4],[5,6]], dtype=torch.float64, device=cuda0)
else:
    print("No GPU available. Using CPU.")

cuda0 = torch.device('cuda', 0)
cuda1 = torch.device('cuda', 1)
cpu = torch.device('cpu')



No GPU available. Using CPU.


### **tensor data type**
![**tensor data type**](https://miro.medium.com/v2/resize:fit:1100/format:webp/1*CHitOyDsG5fXhR80cAT3Ag.png)

In [10]:
# tensor transfer to numpy
tsr2numpy = tsr.numpy()
print('numpy', tsr2numpy)
print('type:', type(tsr2numpy))


numpy [[1. 1. 1.]
 [1. 1. 1.]]
type: <class 'numpy.ndarray'>


In [11]:
# numpy transfer to tensor

'''
torch.Tensor
torch.tensor
torch.as_tensor
torch.from_numpy

'''
arr = np.array([[1,2,3],[4,5,6]])

#1 sol
arr2tsr_1 = torch.tensor(arr)
print("tensor:", arr2tsr_1)
print("dtype:", arr2tsr_1.dtype)

#2 sol
arr2tsr_2 = torch.Tensor(arr)
print("tensor:", arr2tsr_2)
print("dtype:", arr2tsr_2.dtype)

#3 sol
arr2tsr_3 = torch.as_tensor(arr)
print("tensor:", arr2tsr_3)
print("dtype:", arr2tsr_3.dtype)

#4 sol
arr2tsr_4 = torch.from_numpy(arr)
print("tensor:", arr2tsr_4)
print("dtype:", arr2tsr_4.dtype)




tensor: tensor([[1, 2, 3],
        [4, 5, 6]], dtype=torch.int32)
dtype: torch.int32
tensor: tensor([[1., 2., 3.],
        [4., 5., 6.]])
dtype: torch.float32
tensor: tensor([[1, 2, 3],
        [4, 5, 6]], dtype=torch.int32)
dtype: torch.int32
tensor: tensor([[1, 2, 3],
        [4, 5, 6]], dtype=torch.int32)
dtype: torch.int32


In [12]:
# auto_grad
# 設定 requires_grad 指定參數是否追蹤

# 指定tensor
tsr = torch.tensor([[1,2],[3,4],[5,6]], dtype=torch.float64, requires_grad=True)

# 隨機tensor
tsr_randn = torch.randn(2, 3, requires_grad=True)

print(tsr)
print(tsr_randn)


tensor([[1., 2.],
        [3., 4.],
        [5., 6.]], dtype=torch.float64, requires_grad=True)
tensor([[ 1.0382, -1.6673, -1.3184],
        [ 1.1860,  0.7999, -0.2902]], requires_grad=True)


In [13]:
# 梯度計算
# 建立隨機數值的 Tensor 並設定 requires_grad=True
x = torch.randn(2, 3, requires_grad=True)
y = torch.randn(2, 3, requires_grad=True)
z = torch.randn(2, 3, requires_grad=True)

# 計算式子
# b = x*y + z
a = x * y
print('a', a)
b = a + z
print('b', b)
c = torch.sum(b)
print('c', c)

# 計算梯度
c.backward()
# 查看 x 的梯度值
print(x.grad)



a tensor([[ 0.0621,  1.6762,  2.9234],
        [-2.9613, -0.0165,  0.2321]], grad_fn=<MulBackward0>)
b tensor([[ 0.4735,  1.8257,  2.7539],
        [-3.7614,  1.6107,  0.8826]], grad_fn=<AddBackward0>)
c tensor(3.7850, grad_fn=<SumBackward0>)
tensor([[-0.8030, -1.6796,  1.6454],
        [ 1.6146,  0.0370,  0.1649]])


In [14]:
# 停止梯度計算

'''
detach()
with wotch.no_grad()
@torch.no_grad()
with torch.inference_mode()
@torch.inference_mode()

'''

# 建立隨機數值的 Tensor 並設定 requires_grad=True
x = torch.randn(2, 3, requires_grad=True)
y = torch.randn(2, 3, requires_grad=True)
z = torch.randn(2, 3, requires_grad=True)



In [15]:
# 計算式子
a = x * y
b = a + z
c = torch.sum(b)

# 設定 detach()
d = x.detach()

# 查看是否追蹤 d 的梯度計算及數值
print("d requires grad:", d.requires_grad)
print("d grad:", d)
print("d grad:", d.grad)


d requires grad: False
d grad: tensor([[-1.7193, -1.0222, -0.1774],
        [-0.8746, -0.5173,  0.0445]])
d grad: None


In [16]:
# 建立隨機數值的 Tensor 並設定 requires_grad=True
x = torch.randn(2, 3, requires_grad=True)
print('set x requires_grad:', x.requires_grad)
y = torch.randn(2, 3, requires_grad=True)
z = torch.randn(2, 3, requires_grad=True)
# 計算式子
a = x * y
b = a + z

# 輸出
c = torch.sum(b) 
print('org c requires_grad:', c.requires_grad)



set x requires_grad: True
org c requires_grad: True


In [17]:
# 建立隨機數值的 Tensor 並設定 requires_grad=True
x = torch.randn(2, 3, requires_grad=True)
print('set x requires_grad:', x.requires_grad)
y = torch.randn(2, 3, requires_grad=True)
z = torch.randn(2, 3, requires_grad=True)

# 並設定 requires_grad=False
with torch.no_grad():
   a = x * y
   b = a + z
   c = torch.sum(b)
   print("no_grad org c requires_grad:", c.requires_grad)

set x requires_grad: True
no_grad org c requires_grad: False


## 資料讀取
### torch.utils.data.


In [18]:
# torch.utils.data.DataChunk
# 若要定義自己的數據集，需要繼承 Datasets 抽象類別，以及重新 override __init__()、__getitem__()、__len__()。

import torch
import torchvision
from torch.utils.data import Dataset

'''

## template

class myDataset(Dataset):
    def __init__(self):
      # 定義初始化參數
      # 讀取資料集路徑

    def __getitem__(self, index):
      # 讀取每次迭代的資料集中第 idx  資料
      # 進行前處理 (torchvision.Transform 等)
        return 資料和 label

    def __len__(self):
      # 計算資料集總共數量
        return 資料集總數

'''


IndentationError: expected an indented block after function definition on line 9 (1651368747.py, line 13)

In [19]:
from torchvision.datasets import ImageFolder
image_folder = ImageFolder('./dog_cat_data/dataset/training_set', transform=None, target_transform=None)
print(image_folder.class_to_idx)

{'cats': 0, 'dogs': 1}


In [20]:
from torchvision.datasets import ImageFolder
from torch.utils.data import Dataset
from torch.utils.data import DataLoader
from torchvision import transforms

train_transform = transforms.Compose([
                  transforms.Resize((256, 256)),
                  transforms.ToTensor(),
                  transforms.Normalize([0.485, 0.456, 0.406], [0.229, 0.224, 0.225])
])
# 使用 torchvision.datasets.ImageFolder 讀取貓狗資料
image_folder = ImageFolder('./dog_cat_data/dataset/training_set', transform=train_transform, target_transform=None)
# 建立 DataLoader，shuffle 為 True 表示會將資料進行打亂
data_loader = DataLoader(dataset = image_folder, batch_size= 1, shuffle= True, num_workers= 4)
# 列印數據
for batch_idx, (data, target) in enumerate(data_loader):
     print("data:", data)
     print("label:", target)

     if batch_idx == 0:
          break



data: tensor([[[[ 0.1597, -0.0116,  0.0912,  ...,  0.5707,  0.3994,  0.2624],
          [ 0.2111, -0.0972,  0.2282,  ...,  0.5022,  0.4679,  0.4508],
          [ 0.2111,  0.2282,  0.2967,  ...,  0.3481,  0.4337,  0.5022],
          ...,
          [ 0.9817,  0.9988,  1.0159,  ...,  0.9474,  0.9646,  0.9817],
          [ 0.9303,  0.9474,  0.9817,  ...,  0.9988,  1.0159,  1.0159],
          [ 0.8789,  0.9132,  0.9474,  ...,  0.9988,  1.0159,  1.0159]],

         [[ 0.0301, -0.1275,  0.0126,  ...,  0.8704,  0.6779,  0.5203],
          [ 0.1001, -0.1975,  0.1702,  ...,  0.7829,  0.7304,  0.6954],
          [ 0.1176,  0.1702,  0.2402,  ...,  0.6078,  0.6779,  0.7479],
          ...,
          [ 0.9405,  0.9405,  0.9755,  ...,  0.8179,  0.8529,  0.8704],
          [ 0.9055,  0.9055,  0.9405,  ...,  0.8354,  0.8529,  0.8529],
          [ 0.8529,  0.8704,  0.8880,  ...,  0.8354,  0.8529,  0.8529]],

         [[ 0.3393,  0.1999,  0.3742,  ...,  1.3851,  1.2108,  1.0539],
          [ 0.4091,  0.1

In [ ]:
# 內建資料集下載 CIFAR10
import torchvision
cifar_data = torchvision.datasets.CIFAR10(root=r"C:\Users\xdxd2\Sunny_VS_worksapce\Sunny_python\lee hung yi\ML2021-Spring\Pytorch", train=True, download=True)

  0%|          | 0/170498071 [00:00<?, ?it/s]

Extracting C:\Users\xdxd2\Sunny_VS_worksapce\Sunny_python\lee hung yi\ML2021-Spring\Pytorch\cifar-10-python.tar.gz to C:\Users\xdxd2\Sunny_VS_worksapce\Sunny_python\lee hung yi\ML2021-Spring\Pytorch


In [49]:
from torch.utils.data import Dataset
import os
import cv2

class my_cat_data(Dataset):
    def __init__(self, root_dir, label_dir):
        self.root_dir = root_dir
        self.label_dir = label_dir
        self.path = os.path.join(self.root_dir, self.label_dir)
        self.img_path = os.listdir(self.path)

    def __getitem__(self, index):
        img_name = self.img_path[index]
        img_item_path = os.path.join(self.root_dir, self.label_dir, img_name)
        
        img = cv2.imread(img_item_path)
        # cv2.imshow('Image', img)
        # cv2.waitKey(0)  # 等待用户按下任意键
        # cv2.destroyAllWindows()  # 关闭图像窗口

        label = self.label_dir
        label_ = -1
        if label == "cats":
            label_ = 1
        elif label == "dogs":
            label_ = 0
        else:
            lable_ = 2

        return img, label_

    def __len__(self):

        return len(self.img_path)



In [77]:
# 嘗試讀取圖片
root_dir = r"./dog_cat_data/dataset/training_set/"
label_dir = "cats"

animal_dataset = my_cat_data(root_dir, label_dir)

# # 读取图像文件
image = animal_dataset[0][0]

# 检查图像是否成功加载
if image is not None:
    # 图像加载成功，可以在这里进行处理
    # 例如，显示图像
    cv2.imshow('Image', image)
    cv2.waitKey(0)  # 等待用户按下任意键
    cv2.destroyAllWindows()  # 关闭图像窗口
else:
    # 图像加载失败
    print('无法加载图像')

In [78]:
# 整合數據集

root_dir = r"./dog_cat_data/dataset/training_set/"
cats_label_dir = "cats"
dogs_label_dir = "dogs"

cats_dataset = my_cat_data(root_dir, cats_label_dir)
dogs_dataset = my_cat_data(root_dir, dogs_label_dir)

animals_dataset = cats_dataset + dogs_dataset

