<a href="https://colab.research.google.com/github/ga642381/ML2021-Spring/blob/main/Pytorch/Pytorch_Tutorial.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Pytorch Tutorial**


In [1]:
import torch

**1. Pytorch Documentation Explanation with torch.max**



In [11]:
x = torch.randn(4,5)
y = torch.randn(4,5)
z = torch.randn(4,5)
print(x)
print(y)
print(z)

tensor([[ 1.4241, -0.4359, -0.5245,  0.8813, -1.6705],
        [-0.4669, -1.1697,  2.1302,  0.8605,  0.3356],
        [ 0.0107,  1.0696,  0.7299, -0.6075,  1.0182],
        [ 1.3348,  0.5440,  1.1779,  0.4228,  0.7294]])
tensor([[ 1.0212, -1.8702,  1.0316, -0.8384, -0.2813],
        [ 1.1617,  0.5617,  0.9984, -2.0167,  0.4229],
        [-0.4532, -0.5872,  1.8584,  0.0454, -0.4409],
        [ 0.1873,  1.8189,  0.5468, -0.5044, -0.5878]])
tensor([[-0.3400, -1.2494, -2.7701,  0.0660, -1.7955],
        [ 0.9107, -0.2204, -0.6423,  1.1551,  1.4723],
        [ 0.9660, -0.1718, -0.2237,  0.8619, -0.4340],
        [ 1.5165,  0.4455, -0.4338, -0.4695, -0.9770]])


In [12]:
# 1. max of entire tensor (torch.max(input) → Tensor)
m = torch.max(x)
print(m)

tensor(2.1302)


In [20]:
x.shape

torch.Size([4, 5])

In [22]:
# 2. max along a dimension (torch.max(input, dim, keepdim=False, *, out=None) → (Tensor, LongTensor))
m, idx = torch.max(x,0)
print(m)
print(idx)

tensor([1.4241, 1.0696, 2.1302, 0.8813, 1.0182])
tensor([0, 2, 1, 0, 2])


In [23]:
# 2-2
m, idx = torch.max(input=x,dim=0)
print(m)
print(idx)

tensor([1.4241, 1.0696, 2.1302, 0.8813, 1.0182])
tensor([0, 2, 1, 0, 2])


In [24]:
# 2-3
m, idx = torch.max(x,0,False)
print(m)
print(idx)

tensor([1.4241, 1.0696, 2.1302, 0.8813, 1.0182])
tensor([0, 2, 1, 0, 2])


In [25]:
# 2-4
m, idx = torch.max(x,dim=0,keepdim=True)
print(m)
print(idx)

tensor([[1.4241, 1.0696, 2.1302, 0.8813, 1.0182]])
tensor([[0, 2, 1, 0, 2]])


In [27]:
# 2-5
p = (m,idx)
torch.max(x,0,False,out=p)
print(p[0])
print(p[1])
print(p)


tensor([1.4241, 1.0696, 2.1302, 0.8813, 1.0182])
tensor([0, 2, 1, 0, 2])
(tensor([1.4241, 1.0696, 2.1302, 0.8813, 1.0182]), tensor([0, 2, 1, 0, 2]))


In [28]:
# 2-6
p = (m,idx)
torch.max(x,0,False,p)
print(p[0])
print(p[1])

TypeError: max() received an invalid combination of arguments - got (Tensor, int, bool, tuple), but expected one of:
 * (Tensor input)
 * (Tensor input, Tensor other, *, Tensor out)
      didn't match because some of the arguments have invalid types: (Tensor, !int!, !bool!, !tuple!)
 * (Tensor input, int dim, bool keepdim, *, tuple of Tensors out)
 * (Tensor input, name dim, bool keepdim, *, tuple of Tensors out)


In [29]:
# 2-7
m, idx = torch.max(x,True)

TypeError: max() received an invalid combination of arguments - got (Tensor, bool), but expected one of:
 * (Tensor input)
 * (Tensor input, Tensor other, *, Tensor out)
 * (Tensor input, int dim, bool keepdim, *, tuple of Tensors out)
 * (Tensor input, name dim, bool keepdim, *, tuple of Tensors out)


In [30]:
# 3. max(choose max) operators on two tensors (torch.max(input, other, *, out=None) → Tensor)
t = torch.max(x,y)
print(t)

tensor([[ 1.4241, -0.4359,  1.0316,  0.8813, -0.2813],
        [ 1.1617,  0.5617,  2.1302,  0.8605,  0.4229],
        [ 0.0107,  1.0696,  1.8584,  0.0454,  1.0182],
        [ 1.3348,  1.8189,  1.1779,  0.4228,  0.7294]])


**2. Common errors**



The following code blocks show some common errors while using the torch library. First, execute the code with error, and then execute the next code block to fix the error. You need to change the runtime to GPU.


In [31]:
import torch

In [32]:
# 1. different device error
model = torch.nn.Linear(5,1).to("cuda:0")
x = torch.Tensor([1,2,3,4,5]).to("cpu")
y = model(x)

AssertionError: Torch not compiled with CUDA enabled

In [ ]:
# 1. different device error (fixed)
x = torch.Tensor([1,2,3,4,5]).to("cuda:0")
y = model(x)
print(y.shape)

torch.Size([1])


In [76]:
# 2. mismatched dimensions error
x = torch.randn(4,5)
y= torch.randn(5,4)
z = x + y

RuntimeError: The size of tensor a (5) must match the size of tensor b (4) at non-singleton dimension 1

In [77]:
# 2. mismatched dimensions error (fixed)
y= y.transpose(0,1)
z = x + y
print(z.shape)

torch.Size([4, 5])


In [ ]:
# 3. cuda out of memory error
import torch
import torchvision.models as models
resnet18 = models.resnet18().to("cuda:0") # Neural Networks for Image Recognition
data = torch.randn(2048,3,244,244) # Create fake data (512 images)
out = resnet18(data.to("cuda:0")) # Use Data as Input and Feed to Model
print(out.shape)


RuntimeError: ignored

In [ ]:
# 3. cuda out of memory error (fixed)
for d in data:
  out = resnet18(d.to("cuda:0").unsqueeze(0))
print(out.shape)

torch.Size([1, 1000])


In [ ]:
# 4. mismatched tensor type
import torch.nn as nn
L = nn.CrossEntropyLoss()
outs = torch.randn(5,5)
labels = torch.Tensor([1,2,3,4,0])
lossval = L(outs,labels) # Calculate CrossEntropyLoss between outs and labels

RuntimeError: ignored

In [ ]:
# 4. mismatched tensor type (fixed)
labels = labels.long()
lossval = L(outs,labels)
print(lossval)

tensor(2.6215)


**3. More on dataset and dataloader**


A dataset is a cluster of data in a organized way. A dataloader is a loader which can iterate through the data set.

Let a dataset be the English alphabets "abcdefghijklmnopqrstuvwxyz"

In [78]:
dataset = "abcdefghijklmnopqrstuvwxyz"

A simple dataloader could be implemented with the python code "for"

In [79]:
for datapoint in dataset:
  print(datapoint)

a
b
c
d
e
f
g
h
i
j
k
l
m
n
o
p
q
r
s
t
u
v
w
x
y
z


When using the dataloader, we often like to shuffle the data. This is where torch.utils.data.DataLoader comes in handy. If each data is an index (0,1,2...) from the view of torch.utils.data.DataLoader, shuffling can simply be done by shuffling an index array. 



torch.utils.data.DataLoader will need two information to fulfill its role. First, it needs to know the length of the data. Second, once torch.utils.data.DataLoader outputs the index of the shuffling results, the dataset needs to return the corresponding data.

Therefore, torch.utils.data.Dataset provides the information by two functions, `__len__()` and `__getitem__()` to support torch.utils.data.Dataloader

In [80]:
import torch
import torch.utils.data

class ExampleDataset(torch.utils.data.Dataset):
  def __init__(self):
    self.data = "abcdefghijklmnopqrstuvwxyz"
  
  def __getitem__(self,idx): # if the index is idx, what will be the data?
    return self.data[idx]
  
  def __len__(self): # What is the length of the dataset
    return len(self.data)

dataset1 = ExampleDataset() # create the dataset
dataloader = torch.utils.data.DataLoader(dataset = dataset1,shuffle = True, batch_size = 1)
for datapoint in dataloader:
  print(datapoint)

['y']
['e']
['v']
['r']
['d']
['x']
['n']
['w']
['p']
['k']
['s']
['q']
['j']
['h']
['a']
['g']
['i']
['c']
['u']
['z']
['m']
['t']
['o']
['l']
['b']
['f']


A simple data augmentation technique can be done by changing the code in `__len__()` and `__getitem__()`. Suppose we want to double the length of the dataset by adding in the uppercase letters, using only the lowercase dataset, you can change the dataset to the following.

In [130]:
import torch.utils.data 
class ExampleDataset(torch.utils.data.Dataset):
  def __init__(self):
    self.data = "abcdefghijklmnopqrstuvwxyz"
  
  def __getitem__(self,idx): # if the index is idx, what will be the data?
    if idx >= len(self.data): # if the index >= 26, return upper case letter
      return self.data[idx%26].upper()
    else: # if the index < 26, return lower case, return lower case letter
      return self.data[idx]
  
  def __len__(self): # What is the length of the dataset
    return 4 * len(self.data) # The length is now twice as large

dataset1 = ExampleDataset() # create the dataset
dataloader = torch.utils.data.DataLoader(dataset = dataset1,shuffle = True,batch_size = 1)
for datapoint in dataloader:
  print(datapoint)

['W']
['D']
['O']
['b']
['O']
['N']
['p']
['E']
['K']
['H']
['D']
['h']
['M']
['n']
['I']
['D']
['T']
['z']
['B']
['k']
['U']
['c']
['P']
['R']
['B']
['G']
['J']
['V']
['M']
['q']
['s']
['t']
['Q']
['r']
['S']
['X']
['F']
['K']
['f']
['W']
['i']
['Y']
['T']
['C']
['d']
['A']
['C']
['o']
['R']
['Q']
['U']
['T']
['u']
['N']
['J']
['V']
['H']
['C']
['A']
['B']
['e']
['S']
['E']
['G']
['l']
['P']
['Z']
['L']
['J']
['M']
['S']
['H']
['L']
['U']
['Z']
['g']
['Z']
['R']
['N']
['A']
['Q']
['I']
['v']
['y']
['X']
['G']
['O']
['F']
['I']
['a']
['W']
['x']
['P']
['w']
['L']
['Y']
['F']
['E']
['V']
['m']
['Y']
['X']
['j']
['K']


In [ ]:
import torch.utils.data 
class ExampleDataset(torch.utils.data.Dataset):
  def __init__(self):
    self.data = "abcdefghijklmnopqrstuvwxyz"
  
  def __getitem__(self,idx): # if the index is idx, what will be the data?
    if idx >= len(self.data): # if the index >= 26, return upper case letter
      return self.data[idx%26].upper()
    else: # if the index < 26, return lower case, return lower case letter
      return self.data[idx]
  
  def __len__(self): # What is the length of the dataset
    return 4 * len(self.data) # The length is now twice as large

dataset1 = ExampleDataset() # create the dataset
dataloader = torch.utils.data.DataLoader(dataset = dataset1,shuffle = True,batch_size = 1)
for datapoint in dataloader:
  print(datapoint)

['W']
['D']
['O']
['b']
['O']
['N']
['p']
['E']
['K']
['H']
['D']
['h']
['M']
['n']
['I']
['D']
['T']
['z']
['B']
['k']
['U']
['c']
['P']
['R']
['B']
['G']
['J']
['V']
['M']
['q']
['s']
['t']
['Q']
['r']
['S']
['X']
['F']
['K']
['f']
['W']
['i']
['Y']
['T']
['C']
['d']
['A']
['C']
['o']
['R']
['Q']
['U']
['T']
['u']
['N']
['J']
['V']
['H']
['C']
['A']
['B']
['e']
['S']
['E']
['G']
['l']
['P']
['Z']
['L']
['J']
['M']
['S']
['H']
['L']
['U']
['Z']
['g']
['Z']
['R']
['N']
['A']
['Q']
['I']
['v']
['y']
['X']
['G']
['O']
['F']
['I']
['a']
['W']
['x']
['P']
['w']
['L']
['Y']
['F']
['E']
['V']
['m']
['Y']
['X']
['j']
['K']
