# 1-3 PyTorch 數值型態與基本運算

##  PyTorch 數值型態

In [2]:
import torch
import numpy as np

In [3]:
torch.__version__

'1.13.1+cpu'

In [4]:
if torch.cuda.is_available():
    # Get the number of available GPUs
    num_gpus = torch.cuda.device_count()
    
    # Get the name of the current GPU
    current_gpu_name = torch.cuda.get_device_name(0)  # Assuming you have at least one GPU
    
    print(f"Number of available GPUs: {num_gpus}")
    print(f"Current GPU name: {current_gpu_name}")
       
    # Now, operations will be performed on the GPU by default if available
    cuda0 = torch.device('cuda:0')
    tsr = torch.tensor([[1,2],[3,4],[5,6]], dtype=torch.float64, device=cuda0)
else:
    print("No GPU available. Using CPU.")

cuda0 = torch.device('cuda', 0)
cuda1 = torch.device('cuda', 1)
cpu = torch.device('cpu')

No GPU available. Using CPU.


## tensor 創建

In [5]:
tsr = torch.tensor([[1,2],[3,4],[5,6]]); tsr

tensor([[1, 2],
        [3, 4],
        [5, 6]])

In [7]:
# 創建一個 2x3 的零矩陣
tensor1 = torch.zeros(2, 3)
print("零矩陣:")
print(tensor1)

# 創建一個 2x3 的隨機矩陣
tensor2 = torch.rand(2, 3)
print("\n隨機矩陣:")
print(tensor2)

# 創建一個直接由數據構造的 Tensor
data = [[1, 2, 5], [3, 4, 7]]
tensor3 = torch.tensor(data)
print("\n由數據構造的 Tensor:")
print(tensor3)
print(tensor3.dtype)

零矩陣:
tensor([[0., 0., 0.],
        [0., 0., 0.]])

隨機矩陣:
tensor([[0.7716, 0.3164, 0.6444],
        [0.9003, 0.9078, 0.1396]])

由數據構造的 Tensor:
tensor([[1, 2, 5],
        [3, 4, 7]])
torch.int64


## tensor data type


![**tensor data type**](https://miro.medium.com/v2/resize:fit:1100/format:webp/1*CHitOyDsG5fXhR80cAT3Ag.png)

In [14]:
tsr = torch.tensor([[1,2],[3,4]], dtype=torch.float64); tsr

tensor([[1., 2.],
        [3., 4.]], dtype=torch.float64)

In [16]:
# Create a tensor with a single element, 1, using the default tensor type (usually FloatTensor)
tmp_tensor = torch.tensor([1])

# Create a FloatTensor (32-bit floating point) with a single element, 1.01
float_32 = torch.FloatTensor([1.01]) # 32 bits

# Create a DoubleTensor (64-bit floating point) with a single element, 1.01
float_64 = torch.DoubleTensor([1.01]) # 64 bits

# Create an IntTensor (32-bit integer) with a single element, 1
int_32 = torch.IntTensor([1]) # 32 bits

# Create a LongTensor (64-bit integer) with a single element, 1
int_64 = torch.LongTensor([1]) # 64 bits


In [17]:
names = ['float_32', 'float_64', 'int_32', 'int_64']
for i, tmp1 in enumerate([float_32, float_64, int_32, int_64]):
    for j, tmp2 in enumerate([float_32, float_64, int_32, int_64]):
        # print('{} + {}:\t{}'.format(names[i], names[j], (tmp1+tmp2).dtype))
        # print('{} * {}:\t{}'.format(names[i], names[j], (tmp1*tmp2).dtype))
        # print('{} / {}:\t{}'.format(names[i], names[j], (tmp1/tmp2).dtype))


        print(f"{names[i]} + {names[j]}:\t{(tmp1+tmp2).dtype}")
        print(f"{names[i]} * {names[j]}:\t{(tmp1+tmp2).dtype}")
        print(f"{names[i]} / {names[j]}:\t{(tmp1+tmp2).dtype}")

        print("------")

float_32 + float_32:	torch.float32
float_32 * float_32:	torch.float32
float_32 / float_32:	torch.float32
------
float_32 + float_64:	torch.float64
float_32 * float_64:	torch.float64
float_32 / float_64:	torch.float64
------
float_32 + int_32:	torch.float32
float_32 * int_32:	torch.float32
float_32 / int_32:	torch.float32
------
float_32 + int_64:	torch.float32
float_32 * int_64:	torch.float32
float_32 / int_64:	torch.float32
------
float_64 + float_32:	torch.float64
float_64 * float_32:	torch.float64
float_64 / float_32:	torch.float64
------
float_64 + float_64:	torch.float64
float_64 * float_64:	torch.float64
float_64 / float_64:	torch.float64
------
float_64 + int_32:	torch.float64
float_64 * int_32:	torch.float64
float_64 / int_32:	torch.float64
------
float_64 + int_64:	torch.float64
float_64 * int_64:	torch.float64
float_64 / int_64:	torch.float64
------
int_32 + float_32:	torch.float32
int_32 * float_32:	torch.float32
int_32 / float_32:	torch.float32
------
int_32 + float_64:	tor

### tensor <-----> numpy 

In [18]:
# tensor transfer to numpy
tsr2numpy = tsr.numpy()
print('numpy', tsr2numpy)
print('type:', type(tsr2numpy))


numpy [[1. 2.]
 [3. 4.]]
type: <class 'numpy.ndarray'>


In [19]:
# numpy transfer to tensor

'''
torch.Tensor
torch.tensor
torch.as_tensor
torch.from_numpy

'''
arr = np.array([[1,2,3],[4,5,6]])

#1 sol
arr2tsr_1 = torch.tensor(arr)
print("tensor:", arr2tsr_1)
print("dtype:", arr2tsr_1.dtype)

#2 sol
arr2tsr_2 = torch.Tensor(arr)
print("tensor:", arr2tsr_2)
print("dtype:", arr2tsr_2.dtype)

#3 sol
arr2tsr_3 = torch.as_tensor(arr)
print("tensor:", arr2tsr_3)
print("dtype:", arr2tsr_3.dtype)

#4 sol
arr2tsr_4 = torch.from_numpy(arr)
print("tensor:", arr2tsr_4)
print("dtype:", arr2tsr_4.dtype)




tensor: tensor([[1, 2, 3],
        [4, 5, 6]], dtype=torch.int32)
dtype: torch.int32
tensor: tensor([[1., 2., 3.],
        [4., 5., 6.]])
dtype: torch.float32
tensor: tensor([[1, 2, 3],
        [4, 5, 6]], dtype=torch.int32)
dtype: torch.int32
tensor: tensor([[1, 2, 3],
        [4, 5, 6]], dtype=torch.int32)
dtype: torch.int32


## PyTorch Tensor 和資料型態

#### 可微分Tensor的資料型態限制 :
不可隨意改變資料型態：當Tensor被用作模型的參數，且是可微分的（參與反向傳播計算），其資料型態不能隨意改變。

#### PyTorch模型參數的預設資料型態 :
預設為Float32：PyTorch中模型參數的預設資料型態是32位浮點數（Float32）。這提供了足夠的精度，同時節省記憶體和計算時間。

#### Numpy預設資料型態與轉換注意事項 :
Numpy預設為Float64：Numpy的預設浮點數資料型態是Double（Float64），這與PyTorch的預設不同。
轉換時的注意事項：在將Numpy陣列轉換成PyTorch Tensor時，需要特別注意這一點。直接轉換可能導致效能降低或不必要的資源消耗。



In [10]:
import torch
import torchvision
mobilenet_v2 = torchvision.models.mobilenet_v2(pretrained=True)

mobilenet_v2.eval() 

dummy_input = torch.randn(1, 3, 224, 224)
print("模型預測前", dummy_input.dtype)

tmp = mobilenet_v2(dummy_input)

print("模型預測前", tmp.dtype)
print('---------')

C:\Users\xdxd2\AppData\Roaming\Python\Python310\site-packages\torchvision\models\_utils.py:208: UserWarning: The parameter 'pretrained' is deprecated since 0.13 and may be removed in the future, please use 'weights' instead.
  warnings.warn(
C:\Users\xdxd2\AppData\Roaming\Python\Python310\site-packages\torchvision\models\_utils.py:223: UserWarning: Arguments other than a weight enum or `None` for 'weights' are deprecated since 0.13 and may be removed in the future. The current behavior is equivalent to passing `weights=MobileNet_V2_Weights.IMAGENET1K_V1`. You can also use `weights=MobileNet_V2_Weights.DEFAULT` to get the most up-to-date weights.
  warnings.warn(msg)
Downloading: "https://download.pytorch.org/models/mobilenet_v2-b0353104.pth" to C:\Users\xdxd2/.cache\torch\hub\checkpoints\mobilenet_v2-b0353104.pth


  0%|          | 0.00/13.6M [00:00<?, ?B/s]

模型預測前 torch.float32
模型預測前 torch.float32
---------


如果我們沒有注意到輸入的資料格式，直接把numpy的array轉成torch tensor輸入到模型內。

In [24]:
import cv2
import numpy as np
img = cv2.imread('cat.jpg')
img = cv2.resize(img, (224,224))

# numpy array
img = np.array(img)/255
print("- numpy array")
print(img.shape)
print(img.dtype)
print("")

# torch array
img = torch.tensor(img)

'''
permute: 
2 moves the original third dimension (color channels) to the first position.
0 moves the original first dimension (height) to the second position.
1 moves the original second dimension (width) to the third position.
'''

img = img.permute(2, 0, 1)
print("- torch tensor")
print(img.shape)
print(img.dtype)
print("")


# change dimension
img=img.unsqueeze(0)
print("- expand dimension")
print(img.shape)
print(img.dtype)


- numpy array
(224, 224, 3)
float64

- torch tensor
torch.Size([3, 224, 224])
torch.float64

- expand dimension
torch.Size([1, 3, 224, 224])
torch.float64


In [13]:
## float64 送進模型會報錯

tmp = mobilenet_v2(img)

RuntimeError: expected scalar type Double but found Float

避免這類型的出錯，盡量在numpy array或是image型態轉成torch tensor時候，就指定他是```torch.FloatTensor```。

In [36]:
import cv2
import numpy as np


img = cv2.imread('cat.jpg')
img = cv2.resize(img, (224,224))
img = np.array(img)/255


# 轉型 float32
img = torch.FloatTensor(img)

img = img.permute(2, 0, 1)

img=img.unsqueeze(0)
tmp = mobilenet_v2(img)
print(tmp.shape)



torch.Size([1, 1000])


## PyTorch基本運算


## Numpy-Like Implementation 

In [43]:
import numpy as np
a = np.array([[1,2,3],
              [4,5,6]])
b = np.array([[2,2,2],
              [3,3,3]])
c = np.array([[1,2],
              [3,4],
              [5,6]])


print(f'元素點對點相乘(方法1:np.multiply(a,b)):\n{np.multiply(a,b)}')
print(f'元素點對點相乘(方法2:a*b):\n{a*b}')

print("")

print(f'矩陣相乘(方法1: np.dot(a,c)):\n{np.dot(a,c)}')
print(f'矩陣相乘(方法2: a.dot(c)):\n{a.dot(c)}')
print(f'矩陣相乘(方法3: np.matmul(a,c)):\n{np.matmul(a,c)}')


元素點對點相乘(方法1:np.multiply(a,b)):
[[ 2  4  6]
 [12 15 18]]
元素點對點相乘(方法2:a*b):
[[ 2  4  6]
 [12 15 18]]

矩陣相乘(方法1: np.dot(a,c)):
[[22 28]
 [49 64]]
矩陣相乘(方法2: a.dot(c)):
[[22 28]
 [49 64]]
矩陣相乘(方法3: np.matmul(a,c)):
[[22 28]
 [49 64]]


看起來```torch.matmul```和```torch.mm```都是進行矩陣內積運算，那```torch.matmul```和```torch.mm```有沒有什麼差異?

```torch.mm```就是一般我們高中數學學的矩陣相乘，```torch.mm(a,b)```的情況，矩陣/向量$a$要能跟矩陣/向量$b$對上<br>
$$a\in R^{(m\times n)}, b\in R^{(n\times k)}，torch.mm(a,b)\in R^{(m\times k)}$$

```torch.matmul```: 除了一般的矩陣內積運算外，他可以達到Python內建廣播運算，叫做broadcasted運算，當兩個tensor的dimension是broadcasted，使用它時候會很有趣。<br>
假設tensor a: $(i\times 1\times n\times m)$ 和 tnesor b: $(k\times m\times p)$<br>
torch.matmul(a,b) = $(i\times k\times n\times p)$

## Torch broadcasted運算

In [45]:
import torch

a = torch.tensor([[[2, 2, 2],
                   [3, 3, 3]]])
print(f'a: {a.shape}')


b = torch.tensor([
    [[[1, 1],
      [1, 1],
      [1, 1]]],
    [[[2, 2],
      [2, 2],
      [2, 2]]],
    [[[3, 3],
      [3, 3],
      [3, 3]]]
])      
print(f'b: {b.shape}')

c = torch.matmul(a, b)
print(f'a * b: {c.shape}')

m = torch.zeros((3, 1, 2, 2))
for i in range(a.shape[0]):
    for j in range(b.shape[0]):
        m[j, i, :, :] = torch.mm(a[i, :, :], b[j, 0, :, :])


# 確認兩種算法是否一樣
print((c - m).pow(2).sum())



a: torch.Size([1, 2, 3])
b: torch.Size([3, 1, 3, 2])
a * b: torch.Size([3, 1, 2, 2])
tensor(0.)


## Numpy broadcasted運算

In [50]:
import numpy as np

a = np.array([[[2, 2, 2],
               [3, 3, 3]]])
print(f'a: {a.shape}')

b = np.array([
    [[[1, 1],
      [1, 1],
      [1, 1]]],
    [[[2, 2],
      [2, 2],
      [2, 2]]],
    [[[3, 3],
      [3, 3],
      [3, 3]]]
])      
print(f'b: {b.shape}')

c = np.matmul(a, b)
print(f'a * b: {c.shape}')

m = np.zeros((3, 1, 2, 2))
for i in range(a.shape[0]):
    for j in range(b.shape[0]):
        m[j, i, :, :] = np.matmul(a[i, :, :], b[j, 0, :, :])


# 確認兩種算法是否一樣
print(((c - m)**2).sum())



a: (1, 2, 3)
b: (3, 1, 3, 2)
a * b: (3, 1, 2, 2)
0.0


## 效能比較 torch array vs numpy array
### 利用broadcasted運算特性可以節省for loop的時間。

In [56]:
import time
import torch

# Define a function to format elapsed time
def format_time(start_time):
    elapsed_time = time.time() - start_time
    return f'{elapsed_time:.4f} seconds'  # Formats time to 4 decimal places

# Create random tensors a and b
a = torch.rand((100, 5, 10))
b = torch.rand((200, 1, 10, 20))
print(f'a: {a.shape}')
print(f'b: {b.shape}')

# Matrix multiplication using torch.matmul
start_time = time.time()
c = torch.matmul(a, b)
print(f'a * b: {c.shape}')
process_time_matmul = time.time() - start_time
print(f'計算時間: {format_time(start_time)}')

# Manual matrix multiplication using for loops
start_time = time.time()
m = torch.zeros((200, 100, 5, 20))
for i in range(a.shape[0]):
    for j in range(b.shape[0]):
        m[j, i, :, :] = torch.mm(a[i, :, :], b[j, 0, :, :])
process_time_loops = time.time() - start_time
print(f'計算時間: {format_time(start_time)}')

print(f"速度差異 {process_time_loops/process_time_matmul:.2f} 倍")
# Calculate and print the absolute sum of differences
difference = (c - m).abs().sum()
print(f'差異總和: {difference}')



a: torch.Size([100, 5, 10])
b: torch.Size([200, 1, 10, 20])
a * b: torch.Size([200, 100, 5, 20])
計算時間: 0.0130 seconds
計算時間: 0.9630 seconds
速度差異 73.99 倍
差異總和: 0.0


In [59]:
import time
import torch

# Define a function to format elapsed time
def format_time(start_time):
    elapsed_time = time.time() - start_time
    return f'{elapsed_time:.4f} seconds'  # Formats time to 4 decimal places

# Create random tensors a and b
a=np.random.rand(100,5,10)
b=np.random.rand(200,1,10,20)
print(f'a: {a.shape}')
print(f'b: {b.shape}')

# Matrix multiplication using torch.matmul
start_time = time.time()
c=np.matmul(a,b)
print(f'a * b: {c.shape}')
process_time_matmul = time.time() - start_time
print(f'計算時間: {format_time(start_time)}')

# Manual matrix multiplication using for loops
start_time = time.time()
m=np.zeros((200,100,5,20))
for i in range(a.shape[0]):
    for j in range(b.shape[0]):
        m[j,i,:,:] = np.matmul(a[i,:,:], b[j,0,:,:])
process_time_loops = time.time() - start_time
print(f'計算時間: {format_time(start_time)}')

print(f"速度差異 {process_time_loops/process_time_matmul:.2f} 倍")
# Calculate and print the absolute sum of differences
difference = np.abs((c - m)).sum()
print(f'差異總和: {difference}')


a: (100, 5, 10)
b: (200, 1, 10, 20)
a * b: (200, 100, 5, 20)
計算時間: 0.0180 seconds
計算時間: 0.1400 seconds
速度差異 7.78 倍
差異總和: 0.0


### 線性代數函數庫 (Torch vs Numpy)

In [66]:
import numpy as np
import torch

a_np = np.array([[6.0, 2.0],
                 [4.0, 5.0]])
a_torch = torch.tensor(a_np)


print("numpy array\n", a_np)

print("torch array\n", a_torch)


numpy array
 [[6. 2.]
 [4. 5.]]
torch array
 tensor([[6., 2.],
        [4., 5.]], dtype=torch.float64)


In [62]:
# normalization
print(np.linalg.norm(a_np))
print(torch.linalg.norm(a_torch))

9.0
tensor(9., dtype=torch.float64)


In [63]:
#
print(np.linalg.inv(a_np))
print(torch.linalg.inv(a_torch))

[[ 0.22727273 -0.09090909]
 [-0.18181818  0.27272727]]
tensor([[ 0.2273, -0.0909],
        [-0.1818,  0.2727]], dtype=torch.float64)


In [60]:
a_np = np.array([[6.0, 2.0],
                 [4.0, 5.0]])

a_np

array([[6., 2.],
       [4., 5.]])

In [61]:
a_torch = torch.tensor(a_np)

a_torch

tensor([[6., 2.],
        [4., 5.]], dtype=torch.float64)